namespace Capstone
{
    partial class New_Category
    {
        /// <summary>
        /// Required designer variable.
        /// </summary>
        private System.ComponentModel.IContainer components = null;

        /// <summary>
        /// Clean up any resources being used.
        /// </summary>
        /// <param name="disposing">true if managed resources should be disposed; otherwise, false.</param>
        protected override void Dispose(bool disposing)
        {
            if (disposing && (components != null))
            {
                components.Dispose();
            }
            base.Dispose(disposing);
        }

        #region Windows Form Designer generated code

        /// <summary>
        /// Required method for Designer support - do not modify
        /// the contents of this method with the code editor.
        /// </summary>
        private void InitializeComponent()
        {
            this.components = new System.ComponentModel.Container();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges borderEdges8 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges borderEdges7 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges borderEdges6 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges borderEdges5 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges borderEdges4 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges borderEdges3 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges borderEdges2 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges borderEdges1 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties5 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties6 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties7 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties8 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            System.ComponentModel.ComponentResourceManager resources = new System.ComponentModel.ComponentResourceManager(typeof(New_Category));
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties1 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties2 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties3 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties4 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            this.gunaElipse1 = new Guna.UI.WinForms.GunaElipse(this.components);
            this.gunaDragControl1 = new Guna.UI.WinForms.GunaDragControl(this.components);
            this.loginBtn = new Guna.UI.WinForms.GunaButton();
            this.gunaControlBox1 = new Guna.UI.WinForms.GunaControlBox();
            this.gunaControlBox2 = new Guna.UI.WinForms.GunaControlBox();
            this.profilePicBox = new Bunifu.UI.WinForms.BunifuPictureBox();
            this.GunaPictureBox5 = new Guna.UI.WinForms.GunaPictureBox();
            this.Label2 = new System.Windows.Forms.Label();
            this.Label3 = new System.Windows.Forms.Label();
            this.BunifuPictureBox1 = new Bunifu.UI.WinForms.BunifuPictureBox();
            this.Label1 = new System.Windows.Forms.Label();
            this.CategoriesBtn = new Bunifu.UI.WinForms.BunifuButton.BunifuButton();
            this.ItemsBtn = new Bunifu.UI.WinForms.BunifuButton.BunifuButton();
            this.InventoryBtn = new Bunifu.UI.WinForms.BunifuButton.BunifuButton();
            this.SalesBtn = new Bunifu.UI.WinForms.BunifuButton.BunifuButton();
            this.SalesReportBtn = new Bunifu.UI.WinForms.BunifuButton.BunifuButton();
            this.UsersBtn = new Bunifu.UI.WinForms.BunifuButton.BunifuButton();
            this.BunifuButton8 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton();
            this.DashboardBtn = new Bunifu.UI.WinForms.BunifuButton.BunifuButton();
            this.GunaElipsePanel1 = new Guna.UI.WinForms.GunaElipsePanel();
            this.label4 = new System.Windows.Forms.Label();
            this.gunaElipsePanel2 = new Guna.UI.WinForms.GunaElipsePanel();
            this.label5 = new System.Windows.Forms.Label();
            this.label6 = new System.Windows.Forms.Label();
            this.categoryNameTxt = new Bunifu.UI.WinForms.BunifuTextBox();
            this.label7 = new System.Windows.Forms.Label();
            this.categoryDescTxt = new Bunifu.UI.WinForms.BunifuTextBox();
            this.gunaElipsePanel3 = new Guna.UI.WinForms.GunaElipsePanel();
            this.addCategoryBtn = new Guna.UI.WinForms.GunaButton();
            ((System.ComponentModel.ISupportInitialize)(this.profilePicBox)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.GunaPictureBox5)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.BunifuPictureBox1)).BeginInit();
            this.GunaElipsePanel1.SuspendLayout();
            this.gunaElipsePanel2.SuspendLayout();
            this.gunaElipsePanel3.SuspendLayout();
            this.SuspendLayout();
            // 
            // gunaElipse1
            // 
            this.gunaElipse1.Radius = 12;
            this.gunaElipse1.TargetControl = this;
            // 
            // gunaDragControl1
            // 
            this.gunaDragControl1.TargetControl = this;
            // 
            // loginBtn
            // 
            this.loginBtn.AnimationHoverSpeed = 0.07F;
            this.loginBtn.AnimationSpeed = 0.03F;
            this.loginBtn.BackColor = System.Drawing.Color.Transparent;
            this.loginBtn.BaseColor = System.Drawing.Color.Transparent;
            this.loginBtn.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(222)))), ((int)(((byte)(196)))), ((int)(((byte)(125)))));
            this.loginBtn.BorderSize = 2;
            this.loginBtn.Cursor = System.Windows.Forms.Cursors.Hand;
            this.loginBtn.DialogResult = System.Windows.Forms.DialogResult.None;
            this.loginBtn.FocusedColor = System.Drawing.Color.Empty;
            this.loginBtn.Font = new System.Drawing.Font("Poppins", 14.25F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.loginBtn.ForeColor = System.Drawing.Color.Black;
            this.loginBtn.Image = null;
            this.loginBtn.ImageSize = new System.Drawing.Size(20, 20);
            this.loginBtn.Location = new System.Drawing.Point(504, 328);
            this.loginBtn.Name = "loginBtn";
            this.loginBtn.OnHoverBaseColor = System.Drawing.Color.FromArgb(((int)(((byte)(222)))), ((int)(((byte)(196)))), ((int)(((byte)(125)))));
            this.loginBtn.OnHoverBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(222)))), ((int)(((byte)(196)))), ((int)(((byte)(125)))));
            this.loginBtn.OnHoverForeColor = System.Drawing.Color.White;
            this.loginBtn.OnHoverImage = null;
            this.loginBtn.OnPressedColor = System.Drawing.Color.White;
            this.loginBtn.Radius = 6;
            this.loginBtn.Size = new System.Drawing.Size(217, 49);
            this.loginBtn.TabIndex = 28;
            this.loginBtn.Text = "Back";
            this.loginBtn.TextAlign = System.Windows.Forms.HorizontalAlignment.Center;
            this.loginBtn.TextRenderingHint = Guna.UI.WinForms.DrawingTextRenderingHint.AntiAlias;
            this.loginBtn.Click += new System.EventHandler(this.loginBtn_Click);
            // 
            // gunaControlBox1
            // 
            this.gunaControlBox1.Anchor = ((System.Windows.Forms.AnchorStyles)((System.Windows.Forms.AnchorStyles.Top | System.Windows.Forms.AnchorStyles.Right)));
            this.gunaControlBox1.AnimationHoverSpeed = 0.07F;
            this.gunaControlBox1.AnimationSpeed = 0.03F;
            this.gunaControlBox1.ControlBoxTheme = Guna.UI.WinForms.FormControlBoxTheme.Custom;
            this.gunaControlBox1.IconColor = System.Drawing.Color.Black;
            this.gunaControlBox1.IconSize = 15F;
            this.gunaControlBox1.ImeMode = System.Windows.Forms.ImeMode.NoControl;
            this.gunaControlBox1.Location = new System.Drawing.Point(1263, 1);
            this.gunaControlBox1.Name = "gunaControlBox1";
            this.gunaControlBox1.OnHoverBackColor = System.Drawing.Color.FromArgb(((int)(((byte)(212)))), ((int)(((byte)(178)))), ((int)(((byte)(84)))));
            this.gunaControlBox1.OnHoverIconColor = System.Drawing.Color.White;
            this.gunaControlBox1.OnPressedColor = System.Drawing.Color.Black;
            this.gunaControlBox1.Size = new System.Drawing.Size(43, 33);
            this.gunaControlBox1.TabIndex = 24;
            this.gunaControlBox1.TextRenderingHint = Guna.UI.WinForms.DrawingTextRenderingHint.AntiAlias;
            // 
            // gunaControlBox2
            // 
            this.gunaControlBox2.Anchor = ((System.Windows.Forms.AnchorStyles)((System.Windows.Forms.AnchorStyles.Top | System.Windows.Forms.AnchorStyles.Right)));
            this.gunaControlBox2.AnimationHoverSpeed = 0.07F;
            this.gunaControlBox2.AnimationSpeed = 0.03F;
            this.gunaControlBox2.ControlBoxTheme = Guna.UI.WinForms.FormControlBoxTheme.Custom;
            this.gunaControlBox2.ControlBoxType = Guna.UI.WinForms.FormControlBoxType.MinimizeBox;
            this.gunaControlBox2.IconColor = System.Drawing.Color.Black;
            this.gunaControlBox2.IconSize = 15F;
            this.gunaControlBox2.Location = new System.Drawing.Point(1219, 0);
            this.gunaControlBox2.Name = "gunaControlBox2";
            this.gunaControlBox2.OnHoverBackColor = System.Drawing.Color.FromArgb(((int)(((byte)(212)))), ((int)(((byte)(178)))), ((int)(((byte)(84)))));
            this.gunaControlBox2.OnHoverIconColor = System.Drawing.Color.White;
            this.gunaControlBox2.OnPressedColor = System.Drawing.Color.Black;
            this.gunaControlBox2.Size = new System.Drawing.Size(43, 33);
            this.gunaControlBox2.TabIndex = 25;
            this.gunaControlBox2.TextRenderingHint = Guna.UI.WinForms.DrawingTextRenderingHint.AntiAlias;
            // 
            // profilePicBox
            // 
            this.profilePicBox.AllowFocused = false;
            this.profilePicBox.Anchor = System.Windows.Forms.AnchorStyles.None;
            this.profilePicBox.AutoSizeHeight = true;
            this.profilePicBox.BorderRadius = 19;
            this.profilePicBox.Cursor = System.Windows.Forms.Cursors.Hand;
            this.profilePicBox.Image = global::Capstone.Properties.Resources.account;
            this.profilePicBox.IsCircle = true;
            this.profilePicBox.Location = new System.Drawing.Point(1248, 39);
            this.profilePicBox.Name = "profilePicBox";
            this.profilePicBox.Size = new System.Drawing.Size(38, 38);
            this.profilePicBox.SizeMode = System.Windows.Forms.PictureBoxSizeMode.Zoom;
            this.profilePicBox.TabIndex = 23;
            this.profilePicBox.TabStop = false;
            this.profilePicBox.Type = Bunifu.UI.WinForms.BunifuPictureBox.Types.Circle;
            this.profilePicBox.Click += new System.EventHandler(this.profilePicBox_Click);
            // 
            // GunaPictureBox5
            // 
            this.GunaPictureBox5.BaseColor = System.Drawing.Color.White;
            this.GunaPictureBox5.Cursor = System.Windows.Forms.Cursors.Hand;
            this.GunaPictureBox5.Image = global::Capstone.Properties.Resources.bell__1_;
            this.GunaPictureBox5.Location = new System.Drawing.Point(1217, 40);
            this.GunaPictureBox5.Name = "GunaPictureBox5";
            this.GunaPictureBox5.Size = new System.Drawing.Size(25, 37);
            this.GunaPictureBox5.SizeMode = System.Windows.Forms.PictureBoxSizeMode.Zoom;
            this.GunaPictureBox5.TabIndex = 22;
            this.GunaPictureBox5.TabStop = false;
            // 
            // Label2
            // 
            this.Label2.AutoSize = true;
            this.Label2.Font = new System.Drawing.Font("Poppins", 15.75F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.Label2.ForeColor = System.Drawing.Color.White;
            this.Label2.Location = new System.Drawing.Point(293, 23);
            this.Label2.Name = "Label2";
            this.Label2.Size = new System.Drawing.Size(231, 37);
            this.Label2.TabIndex = 21;
            this.Label2.Text = "Hi (Name of Owner),";
            // 
            // Label3
            // 
            this.Label3.AutoSize = true;
            this.Label3.Font = new System.Drawing.Font("Poppins", 15.75F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.Label3.ForeColor = System.Drawing.Color.Black;
            this.Label3.Location = new System.Drawing.Point(293, 57);
            this.Label3.Name = "Label3";
            this.Label3.Size = new System.Drawing.Size(459, 37);
            this.Label3.TabIndex = 20;
            this.Label3.Text = "Welcome to Soothing Cafe - Categories";
            // 
            // BunifuPictureBox1
            // 
            this.BunifuPictureBox1.AllowFocused = false;
            this.BunifuPictureBox1.Anchor = System.Windows.Forms.AnchorStyles.None;
            this.BunifuPictureBox1.AutoSizeHeight = true;
            this.BunifuPictureBox1.BorderRadius = 32;
            this.BunifuPictureBox1.Image = global::Capstone.Properties.Resources.logo_soothing_cafe;
            this.BunifuPictureBox1.IsCircle = true;
            this.BunifuPictureBox1.Location = new System.Drawing.Point(13, 14);
            this.BunifuPictureBox1.Name = "BunifuPictureBox1";
            this.BunifuPictureBox1.Size = new System.Drawing.Size(65, 65);
            this.BunifuPictureBox1.SizeMode = System.Windows.Forms.PictureBoxSizeMode.Zoom;
            this.BunifuPictureBox1.TabIndex = 2;
            this.BunifuPictureBox1.TabStop = false;
            this.BunifuPictureBox1.Type = Bunifu.UI.WinForms.BunifuPictureBox.Types.Circle;
            // 
            // Label1
            // 
            this.Label1.AutoSize = true;
            this.Label1.Font = new System.Drawing.Font("Poppins", 15.75F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.Label1.Location = new System.Drawing.Point(84, 28);
            this.Label1.Name = "Label1";
            this.Label1.Size = new System.Drawing.Size(174, 37);
            this.Label1.TabIndex = 3;
            this.Label1.Text = "Soothing Cafe";
            // 
            // CategoriesBtn
            // 
            this.CategoriesBtn.AllowAnimations = true;
            this.CategoriesBtn.AllowMouseEffects = true;
            this.CategoriesBtn.AllowToggling = false;
            this.CategoriesBtn.AnimationSpeed = 200;
            this.CategoriesBtn.AutoGenerateColors = false;
            this.CategoriesBtn.AutoRoundBorders = false;
            this.CategoriesBtn.AutoSizeLeftIcon = true;
            this.CategoriesBtn.AutoSizeRightIcon = true;
            this.CategoriesBtn.BackColor = System.Drawing.Color.Transparent;
            this.CategoriesBtn.BackColor1 = System.Drawing.Color.White;
            this.CategoriesBtn.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("CategoriesBtn.BackgroundImage")));
            this.CategoriesBtn.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.CategoriesBtn.ButtonText = "Categories";
            this.CategoriesBtn.ButtonTextMarginLeft = 0;
            this.CategoriesBtn.ColorContrastOnClick = 45;
            this.CategoriesBtn.ColorContrastOnHover = 45;
            this.CategoriesBtn.Cursor = System.Windows.Forms.Cursors.Hand;
            borderEdges8.BottomLeft = true;
            borderEdges8.BottomRight = true;
            borderEdges8.TopLeft = true;
            borderEdges8.TopRight = true;
            this.CategoriesBtn.CustomizableEdges = borderEdges8;
            this.CategoriesBtn.DialogResult = System.Windows.Forms.DialogResult.None;
            this.CategoriesBtn.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.CategoriesBtn.DisabledFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.CategoriesBtn.DisabledForecolor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.CategoriesBtn.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton.ButtonStates.Pressed;
            this.CategoriesBtn.Font = new System.Drawing.Font("Century Gothic", 14.25F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.CategoriesBtn.ForeColor = System.Drawing.Color.Black;
            this.CategoriesBtn.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.CategoriesBtn.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.CategoriesBtn.IconLeftPadding = new System.Windows.Forms.Padding(11, 3, 3, 3);
            this.CategoriesBtn.IconMarginLeft = 11;
            this.CategoriesBtn.IconPadding = 10;
            this.CategoriesBtn.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.CategoriesBtn.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.CategoriesBtn.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.CategoriesBtn.IconSize = 25;
            this.CategoriesBtn.IdleBorderColor = System.Drawing.Color.White;
            this.CategoriesBtn.IdleBorderRadius = 1;
            this.CategoriesBtn.IdleBorderThickness = 1;
            this.CategoriesBtn.IdleFillColor = System.Drawing.Color.White;
            this.CategoriesBtn.IdleIconLeftImage = global::Capstone.Properties.Resources.category;
            this.CategoriesBtn.IdleIconRightImage = null;
            this.CategoriesBtn.IndicateFocus = false;
            this.CategoriesBtn.Location = new System.Drawing.Point(22, 155);
            this.CategoriesBtn.Name = "CategoriesBtn";
            this.CategoriesBtn.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.CategoriesBtn.OnDisabledState.BorderRadius = 1;
            this.CategoriesBtn.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.CategoriesBtn.OnDisabledState.BorderThickness = 1;
            this.CategoriesBtn.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.CategoriesBtn.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.CategoriesBtn.OnDisabledState.IconLeftImage = null;
            this.CategoriesBtn.OnDisabledState.IconRightImage = null;
            this.CategoriesBtn.onHoverState.BorderColor = System.Drawing.Color.White;
            this.CategoriesBtn.onHoverState.BorderRadius = 1;
            this.CategoriesBtn.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.CategoriesBtn.onHoverState.BorderThickness = 1;
            this.CategoriesBtn.onHoverState.FillColor = System.Drawing.Color.White;
            this.CategoriesBtn.onHoverState.ForeColor = System.Drawing.Color.Black;
            this.CategoriesBtn.onHoverState.IconLeftImage = null;
            this.CategoriesBtn.onHoverState.IconRightImage = null;
            this.CategoriesBtn.OnIdleState.BorderColor = System.Drawing.Color.White;
            this.CategoriesBtn.OnIdleState.BorderRadius = 1;
            this.CategoriesBtn.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.CategoriesBtn.OnIdleState.BorderThickness = 1;
            this.CategoriesBtn.OnIdleState.FillColor = System.Drawing.Color.White;
            this.CategoriesBtn.OnIdleState.ForeColor = System.Drawing.Color.Black;
            this.CategoriesBtn.OnIdleState.IconLeftImage = global::Capstone.Properties.Resources.category;
            this.CategoriesBtn.OnIdleState.IconRightImage = null;
            this.CategoriesBtn.OnPressedState.BorderColor = System.Drawing.Color.White;
            this.CategoriesBtn.OnPressedState.BorderRadius = 1;
            this.CategoriesBtn.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.CategoriesBtn.OnPressedState.BorderThickness = 1;
            this.CategoriesBtn.OnPressedState.FillColor = System.Drawing.Color.White;
            this.CategoriesBtn.OnPressedState.ForeColor = System.Drawing.Color.Black;
            this.CategoriesBtn.OnPressedState.IconLeftImage = null;
            this.CategoriesBtn.OnPressedState.IconRightImage = null;
            this.CategoriesBtn.Size = new System.Drawing.Size(220, 49);
            this.CategoriesBtn.TabIndex = 4;
            this.CategoriesBtn.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.CategoriesBtn.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.CategoriesBtn.TextMarginLeft = 0;
            this.CategoriesBtn.TextPadding = new System.Windows.Forms.Padding(10, 0, 0, 0);
            this.CategoriesBtn.UseDefaultRadiusAndThickness = true;
            this.CategoriesBtn.Click += new System.EventHandler(this.CategoriesBtn_Click);
            // 
            // ItemsBtn
            // 
            this.ItemsBtn.AllowAnimations = true;
            this.ItemsBtn.AllowMouseEffects = true;
            this.ItemsBtn.AllowToggling = false;
            this.ItemsBtn.AnimationSpeed = 200;
            this.ItemsBtn.AutoGenerateColors = false;
            this.ItemsBtn.AutoRoundBorders = false;
            this.ItemsBtn.AutoSizeLeftIcon = true;
            this.ItemsBtn.AutoSizeRightIcon = true;
            this.ItemsBtn.BackColor = System.Drawing.Color.Transparent;
            this.ItemsBtn.BackColor1 = System.Drawing.Color.White;
            this.ItemsBtn.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("ItemsBtn.BackgroundImage")));
            this.ItemsBtn.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.ItemsBtn.ButtonText = "Items";
            this.ItemsBtn.ButtonTextMarginLeft = 0;
            this.ItemsBtn.ColorContrastOnClick = 45;
            this.ItemsBtn.ColorContrastOnHover = 45;
            this.ItemsBtn.Cursor = System.Windows.Forms.Cursors.Hand;
            borderEdges7.BottomLeft = true;
            borderEdges7.BottomRight = true;
            borderEdges7.TopLeft = true;
            borderEdges7.TopRight = true;
            this.ItemsBtn.CustomizableEdges = borderEdges7;
            this.ItemsBtn.DialogResult = System.Windows.Forms.DialogResult.None;
            this.ItemsBtn.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.ItemsBtn.DisabledFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.ItemsBtn.DisabledForecolor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.ItemsBtn.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton.ButtonStates.Pressed;
            this.ItemsBtn.Font = new System.Drawing.Font("Century Gothic", 14.25F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.ItemsBtn.ForeColor = System.Drawing.Color.Black;
            this.ItemsBtn.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.ItemsBtn.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.ItemsBtn.IconLeftPadding = new System.Windows.Forms.Padding(11, 3, 3, 3);
            this.ItemsBtn.IconMarginLeft = 11;
            this.ItemsBtn.IconPadding = 10;
            this.ItemsBtn.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.ItemsBtn.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.ItemsBtn.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.ItemsBtn.IconSize = 25;
            this.ItemsBtn.IdleBorderColor = System.Drawing.Color.White;
            this.ItemsBtn.IdleBorderRadius = 1;
            this.ItemsBtn.IdleBorderThickness = 1;
            this.ItemsBtn.IdleFillColor = System.Drawing.Color.White;
            this.ItemsBtn.IdleIconLeftImage = global::Capstone.Properties.Resources.grocery_bag;
            this.ItemsBtn.IdleIconRightImage = null;
            this.ItemsBtn.IndicateFocus = false;
            this.ItemsBtn.Location = new System.Drawing.Point(22, 210);
            this.ItemsBtn.Name = "ItemsBtn";
            this.ItemsBtn.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.ItemsBtn.OnDisabledState.BorderRadius = 1;
            this.ItemsBtn.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.ItemsBtn.OnDisabledState.BorderThickness = 1;
            this.ItemsBtn.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.ItemsBtn.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.ItemsBtn.OnDisabledState.IconLeftImage = null;
            this.ItemsBtn.OnDisabledState.IconRightImage = null;
            this.ItemsBtn.onHoverState.BorderColor = System.Drawing.Color.White;
            this.ItemsBtn.onHoverState.BorderRadius = 1;
            this.ItemsBtn.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.ItemsBtn.onHoverState.BorderThickness = 1;
            this.ItemsBtn.onHoverState.FillColor = System.Drawing.Color.White;
            this.ItemsBtn.onHoverState.ForeColor = System.Drawing.Color.Black;
            this.ItemsBtn.onHoverState.IconLeftImage = null;
            this.ItemsBtn.onHoverState.IconRightImage = null;
            this.ItemsBtn.OnIdleState.BorderColor = System.Drawing.Color.White;
            this.ItemsBtn.OnIdleState.BorderRadius = 1;
            this.ItemsBtn.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.ItemsBtn.OnIdleState.BorderThickness = 1;
            this.ItemsBtn.OnIdleState.FillColor = System.Drawing.Color.White;
            this.ItemsBtn.OnIdleState.ForeColor = System.Drawing.Color.Black;
            this.ItemsBtn.OnIdleState.IconLeftImage = global::Capstone.Properties.Resources.grocery_bag;
            this.ItemsBtn.OnIdleState.IconRightImage = null;
            this.ItemsBtn.OnPressedState.BorderColor = System.Drawing.Color.White;
            this.ItemsBtn.OnPressedState.BorderRadius = 1;
            this.ItemsBtn.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.ItemsBtn.OnPressedState.BorderThickness = 1;
            this.ItemsBtn.OnPressedState.FillColor = System.Drawing.Color.White;
            this.ItemsBtn.OnPressedState.ForeColor = System.Drawing.Color.Black;
            this.ItemsBtn.OnPressedState.IconLeftImage = null;
            this.ItemsBtn.OnPressedState.IconRightImage = null;
            this.ItemsBtn.Size = new System.Drawing.Size(220, 49);
            this.ItemsBtn.TabIndex = 5;
            this.ItemsBtn.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.ItemsBtn.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.ItemsBtn.TextMarginLeft = 0;
            this.ItemsBtn.TextPadding = new System.Windows.Forms.Padding(-13, 0, 0, 0);
            this.ItemsBtn.UseDefaultRadiusAndThickness = true;
            // 
            // InventoryBtn
            // 
            this.InventoryBtn.AllowAnimations = true;
            this.InventoryBtn.AllowMouseEffects = true;
            this.InventoryBtn.AllowToggling = false;
            this.InventoryBtn.AnimationSpeed = 200;
            this.InventoryBtn.AutoGenerateColors = false;
            this.InventoryBtn.AutoRoundBorders = false;
            this.InventoryBtn.AutoSizeLeftIcon = true;
            this.InventoryBtn.AutoSizeRightIcon = true;
            this.InventoryBtn.BackColor = System.Drawing.Color.Transparent;
            this.InventoryBtn.BackColor1 = System.Drawing.Color.White;
            this.InventoryBtn.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("InventoryBtn.BackgroundImage")));
            this.InventoryBtn.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.InventoryBtn.ButtonText = "Inventory";
            this.InventoryBtn.ButtonTextMarginLeft = 0;
            this.InventoryBtn.ColorContrastOnClick = 45;
            this.InventoryBtn.ColorContrastOnHover = 45;
            this.InventoryBtn.Cursor = System.Windows.Forms.Cursors.Hand;
            borderEdges6.BottomLeft = true;
            borderEdges6.BottomRight = true;
            borderEdges6.TopLeft = true;
            borderEdges6.TopRight = true;
            this.InventoryBtn.CustomizableEdges = borderEdges6;
            this.InventoryBtn.DialogResult = System.Windows.Forms.DialogResult.None;
            this.InventoryBtn.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.InventoryBtn.DisabledFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.InventoryBtn.DisabledForecolor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.InventoryBtn.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton.ButtonStates.Pressed;
            this.InventoryBtn.Font = new System.Drawing.Font("Century Gothic", 14.25F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.InventoryBtn.ForeColor = System.Drawing.Color.Black;
            this.InventoryBtn.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.InventoryBtn.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.InventoryBtn.IconLeftPadding = new System.Windows.Forms.Padding(11, 3, 3, 3);
            this.InventoryBtn.IconMarginLeft = 11;
            this.InventoryBtn.IconPadding = 10;
            this.InventoryBtn.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.InventoryBtn.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.InventoryBtn.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.InventoryBtn.IconSize = 25;
            this.InventoryBtn.IdleBorderColor = System.Drawing.Color.White;
            this.InventoryBtn.IdleBorderRadius = 1;
            this.InventoryBtn.IdleBorderThickness = 1;
            this.InventoryBtn.IdleFillColor = System.Drawing.Color.White;
            this.InventoryBtn.IdleIconLeftImage = global::Capstone.Properties.Resources.warehouse_alt;
            this.InventoryBtn.IdleIconRightImage = null;
            this.InventoryBtn.IndicateFocus = false;
            this.InventoryBtn.Location = new System.Drawing.Point(22, 265);
            this.InventoryBtn.Name = "InventoryBtn";
            this.InventoryBtn.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.InventoryBtn.OnDisabledState.BorderRadius = 1;
            this.InventoryBtn.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.InventoryBtn.OnDisabledState.BorderThickness = 1;
            this.InventoryBtn.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.InventoryBtn.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.InventoryBtn.OnDisabledState.IconLeftImage = null;
            this.InventoryBtn.OnDisabledState.IconRightImage = null;
            this.InventoryBtn.onHoverState.BorderColor = System.Drawing.Color.White;
            this.InventoryBtn.onHoverState.BorderRadius = 1;
            this.InventoryBtn.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.InventoryBtn.onHoverState.BorderThickness = 1;
            this.InventoryBtn.onHoverState.FillColor = System.Drawing.Color.White;
            this.InventoryBtn.onHoverState.ForeColor = System.Drawing.Color.Black;
            this.InventoryBtn.onHoverState.IconLeftImage = null;
            this.InventoryBtn.onHoverState.IconRightImage = null;
            this.InventoryBtn.OnIdleState.BorderColor = System.Drawing.Color.White;
            this.InventoryBtn.OnIdleState.BorderRadius = 1;
            this.InventoryBtn.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.InventoryBtn.OnIdleState.BorderThickness = 1;
            this.InventoryBtn.OnIdleState.FillColor = System.Drawing.Color.White;
            this.InventoryBtn.OnIdleState.ForeColor = System.Drawing.Color.Black;
            this.InventoryBtn.OnIdleState.IconLeftImage = global::Capstone.Properties.Resources.warehouse_alt;
            this.InventoryBtn.OnIdleState.IconRightImage = null;
            this.InventoryBtn.OnPressedState.BorderColor = System.Drawing.Color.White;
            this.InventoryBtn.OnPressedState.BorderRadius = 1;
            this.InventoryBtn.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.InventoryBtn.OnPressedState.BorderThickness = 1;
            this.InventoryBtn.OnPressedState.FillColor = System.Drawing.Color.White;
            this.InventoryBtn.OnPressedState.ForeColor = System.Drawing.Color.Black;
            this.InventoryBtn.OnPressedState.IconLeftImage = null;
            this.InventoryBtn.OnPressedState.IconRightImage = null;
            this.InventoryBtn.Size = new System.Drawing.Size(220, 49);
            this.InventoryBtn.TabIndex = 6;
            this.InventoryBtn.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.InventoryBtn.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.InventoryBtn.TextMarginLeft = 0;
            this.InventoryBtn.TextPadding = new System.Windows.Forms.Padding(5, 0, 0, 0);
            this.InventoryBtn.UseDefaultRadiusAndThickness = true;
            // 
            // SalesBtn
            // 
            this.SalesBtn.AllowAnimations = true;
            this.SalesBtn.AllowMouseEffects = true;
            this.SalesBtn.AllowToggling = false;
            this.SalesBtn.AnimationSpeed = 200;
            this.SalesBtn.AutoGenerateColors = false;
            this.SalesBtn.AutoRoundBorders = false;
            this.SalesBtn.AutoSizeLeftIcon = true;
            this.SalesBtn.AutoSizeRightIcon = true;
            this.SalesBtn.BackColor = System.Drawing.Color.Transparent;
            this.SalesBtn.BackColor1 = System.Drawing.Color.White;
            this.SalesBtn.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("SalesBtn.BackgroundImage")));
            this.SalesBtn.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.SalesBtn.ButtonText = "Sales";
            this.SalesBtn.ButtonTextMarginLeft = 0;
            this.SalesBtn.ColorContrastOnClick = 45;
            this.SalesBtn.ColorContrastOnHover = 45;
            this.SalesBtn.Cursor = System.Windows.Forms.Cursors.Hand;
            borderEdges5.BottomLeft = true;
            borderEdges5.BottomRight = true;
            borderEdges5.TopLeft = true;
            borderEdges5.TopRight = true;
            this.SalesBtn.CustomizableEdges = borderEdges5;
            this.SalesBtn.DialogResult = System.Windows.Forms.DialogResult.None;
            this.SalesBtn.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.SalesBtn.DisabledFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.SalesBtn.DisabledForecolor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.SalesBtn.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton.ButtonStates.Pressed;
            this.SalesBtn.Font = new System.Drawing.Font("Century Gothic", 14.25F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.SalesBtn.ForeColor = System.Drawing.Color.Black;
            this.SalesBtn.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.SalesBtn.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.SalesBtn.IconLeftPadding = new System.Windows.Forms.Padding(11, 3, 3, 3);
            this.SalesBtn.IconMarginLeft = 11;
            this.SalesBtn.IconPadding = 10;
            this.SalesBtn.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.SalesBtn.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.SalesBtn.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.SalesBtn.IconSize = 25;
            this.SalesBtn.IdleBorderColor = System.Drawing.Color.White;
            this.SalesBtn.IdleBorderRadius = 1;
            this.SalesBtn.IdleBorderThickness = 1;
            this.SalesBtn.IdleFillColor = System.Drawing.Color.White;
            this.SalesBtn.IdleIconLeftImage = global::Capstone.Properties.Resources.chart_line_up;
            this.SalesBtn.IdleIconRightImage = null;
            this.SalesBtn.IndicateFocus = false;
            this.SalesBtn.Location = new System.Drawing.Point(22, 320);
            this.SalesBtn.Name = "SalesBtn";
            this.SalesBtn.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.SalesBtn.OnDisabledState.BorderRadius = 1;
            this.SalesBtn.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.SalesBtn.OnDisabledState.BorderThickness = 1;
            this.SalesBtn.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.SalesBtn.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.SalesBtn.OnDisabledState.IconLeftImage = null;
            this.SalesBtn.OnDisabledState.IconRightImage = null;
            this.SalesBtn.onHoverState.BorderColor = System.Drawing.Color.White;
            this.SalesBtn.onHoverState.BorderRadius = 1;
            this.SalesBtn.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.SalesBtn.onHoverState.BorderThickness = 1;
            this.SalesBtn.onHoverState.FillColor = System.Drawing.Color.White;
            this.SalesBtn.onHoverState.ForeColor = System.Drawing.Color.Black;
            this.SalesBtn.onHoverState.IconLeftImage = null;
            this.SalesBtn.onHoverState.IconRightImage = null;
            this.SalesBtn.OnIdleState.BorderColor = System.Drawing.Color.White;
            this.SalesBtn.OnIdleState.BorderRadius = 1;
            this.SalesBtn.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.SalesBtn.OnIdleState.BorderThickness = 1;
            this.SalesBtn.OnIdleState.FillColor = System.Drawing.Color.White;
            this.SalesBtn.OnIdleState.ForeColor = System.Drawing.Color.Black;
            this.SalesBtn.OnIdleState.IconLeftImage = global::Capstone.Properties.Resources.chart_line_up;
            this.SalesBtn.OnIdleState.IconRightImage = null;
            this.SalesBtn.OnPressedState.BorderColor = System.Drawing.Color.White;
            this.SalesBtn.OnPressedState.BorderRadius = 1;
            this.SalesBtn.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.SalesBtn.OnPressedState.BorderThickness = 1;
            this.SalesBtn.OnPressedState.FillColor = System.Drawing.Color.White;
            this.SalesBtn.OnPressedState.ForeColor = System.Drawing.Color.Black;
            this.SalesBtn.OnPressedState.IconLeftImage = null;
            this.SalesBtn.OnPressedState.IconRightImage = null;
            this.SalesBtn.Size = new System.Drawing.Size(220, 49);
            this.SalesBtn.TabIndex = 7;
            this.SalesBtn.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.SalesBtn.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.SalesBtn.TextMarginLeft = 0;
            this.SalesBtn.TextPadding = new System.Windows.Forms.Padding(-14, 0, 0, 0);
            this.SalesBtn.UseDefaultRadiusAndThickness = true;
            // 
            // SalesReportBtn
            // 
            this.SalesReportBtn.AllowAnimations = true;
            this.SalesReportBtn.AllowMouseEffects = true;
            this.SalesReportBtn.AllowToggling = false;
            this.SalesReportBtn.AnimationSpeed = 200;
            this.SalesReportBtn.AutoGenerateColors = false;
            this.SalesReportBtn.AutoRoundBorders = false;
            this.SalesReportBtn.AutoSizeLeftIcon = true;
            this.SalesReportBtn.AutoSizeRightIcon = true;
            this.SalesReportBtn.BackColor = System.Drawing.Color.Transparent;
            this.SalesReportBtn.BackColor1 = System.Drawing.Color.White;
            this.SalesReportBtn.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("SalesReportBtn.BackgroundImage")));
            this.SalesReportBtn.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.SalesReportBtn.ButtonText = "Sales Reports";
            this.SalesReportBtn.ButtonTextMarginLeft = 0;
            this.SalesReportBtn.ColorContrastOnClick = 45;
            this.SalesReportBtn.ColorContrastOnHover = 45;
            this.SalesReportBtn.Cursor = System.Windows.Forms.Cursors.Hand;
            borderEdges4.BottomLeft = true;
            borderEdges4.BottomRight = true;
            borderEdges4.TopLeft = true;
            borderEdges4.TopRight = true;
            this.SalesReportBtn.CustomizableEdges = borderEdges4;
            this.SalesReportBtn.DialogResult = System.Windows.Forms.DialogResult.None;
            this.SalesReportBtn.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.SalesReportBtn.DisabledFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.SalesReportBtn.DisabledForecolor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.SalesReportBtn.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton.ButtonStates.Pressed;
            this.SalesReportBtn.Font = new System.Drawing.Font("Century Gothic", 14.25F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.SalesReportBtn.ForeColor = System.Drawing.Color.Black;
            this.SalesReportBtn.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.SalesReportBtn.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.SalesReportBtn.IconLeftPadding = new System.Windows.Forms.Padding(11, 3, 3, 3);
            this.SalesReportBtn.IconMarginLeft = 11;
            this.SalesReportBtn.IconPadding = 10;
            this.SalesReportBtn.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.SalesReportBtn.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.SalesReportBtn.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.SalesReportBtn.IconSize = 25;
            this.SalesReportBtn.IdleBorderColor = System.Drawing.Color.White;
            this.SalesReportBtn.IdleBorderRadius = 1;
            this.SalesReportBtn.IdleBorderThickness = 1;
            this.SalesReportBtn.IdleFillColor = System.Drawing.Color.White;
            this.SalesReportBtn.IdleIconLeftImage = global::Capstone.Properties.Resources.newspaper;
            this.SalesReportBtn.IdleIconRightImage = null;
            this.SalesReportBtn.IndicateFocus = false;
            this.SalesReportBtn.Location = new System.Drawing.Point(22, 375);
            this.SalesReportBtn.Name = "SalesReportBtn";
            this.SalesReportBtn.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.SalesReportBtn.OnDisabledState.BorderRadius = 1;
            this.SalesReportBtn.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.SalesReportBtn.OnDisabledState.BorderThickness = 1;
            this.SalesReportBtn.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.SalesReportBtn.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.SalesReportBtn.OnDisabledState.IconLeftImage = null;
            this.SalesReportBtn.OnDisabledState.IconRightImage = null;
            this.SalesReportBtn.onHoverState.BorderColor = System.Drawing.Color.White;
            this.SalesReportBtn.onHoverState.BorderRadius = 1;
            this.SalesReportBtn.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.SalesReportBtn.onHoverState.BorderThickness = 1;
            this.SalesReportBtn.onHoverState.FillColor = System.Drawing.Color.White;
            this.SalesReportBtn.onHoverState.ForeColor = System.Drawing.Color.Black;
            this.SalesReportBtn.onHoverState.IconLeftImage = null;
            this.SalesReportBtn.onHoverState.IconRightImage = null;
            this.SalesReportBtn.OnIdleState.BorderColor = System.Drawing.Color.White;
            this.SalesReportBtn.OnIdleState.BorderRadius = 1;
            this.SalesReportBtn.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.SalesReportBtn.OnIdleState.BorderThickness = 1;
            this.SalesReportBtn.OnIdleState.FillColor = System.Drawing.Color.White;
            this.SalesReportBtn.OnIdleState.ForeColor = System.Drawing.Color.Black;
            this.SalesReportBtn.OnIdleState.IconLeftImage = global::Capstone.Properties.Resources.newspaper;
            this.SalesReportBtn.OnIdleState.IconRightImage = null;
            this.SalesReportBtn.OnPressedState.BorderColor = System.Drawing.Color.White;
            this.SalesReportBtn.OnPressedState.BorderRadius = 1;
            this.SalesReportBtn.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.SalesReportBtn.OnPressedState.BorderThickness = 1;
            this.SalesReportBtn.OnPressedState.FillColor = System.Drawing.Color.White;
            this.SalesReportBtn.OnPressedState.ForeColor = System.Drawing.Color.Black;
            this.SalesReportBtn.OnPressedState.IconLeftImage = null;
            this.SalesReportBtn.OnPressedState.IconRightImage = null;
            this.SalesReportBtn.Size = new System.Drawing.Size(220, 49);
            this.SalesReportBtn.TabIndex = 8;
            this.SalesReportBtn.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.SalesReportBtn.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.SalesReportBtn.TextMarginLeft = 0;
            this.SalesReportBtn.TextPadding = new System.Windows.Forms.Padding(23, 0, 0, 0);
            this.SalesReportBtn.UseDefaultRadiusAndThickness = true;
            // 
            // UsersBtn
            // 
            this.UsersBtn.AllowAnimations = true;
            this.UsersBtn.AllowMouseEffects = true;
            this.UsersBtn.AllowToggling = false;
            this.UsersBtn.AnimationSpeed = 200;
            this.UsersBtn.AutoGenerateColors = false;
            this.UsersBtn.AutoRoundBorders = false;
            this.UsersBtn.AutoSizeLeftIcon = true;
            this.UsersBtn.AutoSizeRightIcon = true;
            this.UsersBtn.BackColor = System.Drawing.Color.Transparent;
            this.UsersBtn.BackColor1 = System.Drawing.Color.White;
            this.UsersBtn.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("UsersBtn.BackgroundImage")));
            this.UsersBtn.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.UsersBtn.ButtonText = "Users";
            this.UsersBtn.ButtonTextMarginLeft = 0;
            this.UsersBtn.ColorContrastOnClick = 45;
            this.UsersBtn.ColorContrastOnHover = 45;
            this.UsersBtn.Cursor = System.Windows.Forms.Cursors.Hand;
            borderEdges3.BottomLeft = true;
            borderEdges3.BottomRight = true;
            borderEdges3.TopLeft = true;
            borderEdges3.TopRight = true;
            this.UsersBtn.CustomizableEdges = borderEdges3;
            this.UsersBtn.DialogResult = System.Windows.Forms.DialogResult.None;
            this.UsersBtn.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.UsersBtn.DisabledFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.UsersBtn.DisabledForecolor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.UsersBtn.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton.ButtonStates.Pressed;
            this.UsersBtn.Font = new System.Drawing.Font("Century Gothic", 14.25F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.UsersBtn.ForeColor = System.Drawing.Color.Black;
            this.UsersBtn.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.UsersBtn.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.UsersBtn.IconLeftPadding = new System.Windows.Forms.Padding(11, 3, 3, 3);
            this.UsersBtn.IconMarginLeft = 11;
            this.UsersBtn.IconPadding = 10;
            this.UsersBtn.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.UsersBtn.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.UsersBtn.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.UsersBtn.IconSize = 25;
            this.UsersBtn.IdleBorderColor = System.Drawing.Color.White;
            this.UsersBtn.IdleBorderRadius = 1;
            this.UsersBtn.IdleBorderThickness = 1;
            this.UsersBtn.IdleFillColor = System.Drawing.Color.White;
            this.UsersBtn.IdleIconLeftImage = global::Capstone.Properties.Resources.users;
            this.UsersBtn.IdleIconRightImage = null;
            this.UsersBtn.IndicateFocus = false;
            this.UsersBtn.Location = new System.Drawing.Point(22, 430);
            this.UsersBtn.Name = "UsersBtn";
            this.UsersBtn.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.UsersBtn.OnDisabledState.BorderRadius = 1;
            this.UsersBtn.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.UsersBtn.OnDisabledState.BorderThickness = 1;
            this.UsersBtn.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.UsersBtn.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.UsersBtn.OnDisabledState.IconLeftImage = null;
            this.UsersBtn.OnDisabledState.IconRightImage = null;
            this.UsersBtn.onHoverState.BorderColor = System.Drawing.Color.White;
            this.UsersBtn.onHoverState.BorderRadius = 1;
            this.UsersBtn.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.UsersBtn.onHoverState.BorderThickness = 1;
            this.UsersBtn.onHoverState.FillColor = System.Drawing.Color.White;
            this.UsersBtn.onHoverState.ForeColor = System.Drawing.Color.Black;
            this.UsersBtn.onHoverState.IconLeftImage = null;
            this.UsersBtn.onHoverState.IconRightImage = null;
            this.UsersBtn.OnIdleState.BorderColor = System.Drawing.Color.White;
            this.UsersBtn.OnIdleState.BorderRadius = 1;
            this.UsersBtn.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.UsersBtn.OnIdleState.BorderThickness = 1;
            this.UsersBtn.OnIdleState.FillColor = System.Drawing.Color.White;
            this.UsersBtn.OnIdleState.ForeColor = System.Drawing.Color.Black;
            this.UsersBtn.OnIdleState.IconLeftImage = global::Capstone.Properties.Resources.users;
            this.UsersBtn.OnIdleState.IconRightImage = null;
            this.UsersBtn.OnPressedState.BorderColor = System.Drawing.Color.White;
            this.UsersBtn.OnPressedState.BorderRadius = 1;
            this.UsersBtn.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.UsersBtn.OnPressedState.BorderThickness = 1;
            this.UsersBtn.OnPressedState.FillColor = System.Drawing.Color.White;
            this.UsersBtn.OnPressedState.ForeColor = System.Drawing.Color.Black;
            this.UsersBtn.OnPressedState.IconLeftImage = null;
            this.UsersBtn.OnPressedState.IconRightImage = null;
            this.UsersBtn.Size = new System.Drawing.Size(220, 49);
            this.UsersBtn.TabIndex = 9;
            this.UsersBtn.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.UsersBtn.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.UsersBtn.TextMarginLeft = 0;
            this.UsersBtn.TextPadding = new System.Windows.Forms.Padding(-16, 0, 0, 0);
            this.UsersBtn.UseDefaultRadiusAndThickness = true;
            // 
            // BunifuButton8
            // 
            this.BunifuButton8.AllowAnimations = true;
            this.BunifuButton8.AllowMouseEffects = true;
            this.BunifuButton8.AllowToggling = false;
            this.BunifuButton8.AnimationSpeed = 200;
            this.BunifuButton8.AutoGenerateColors = false;
            this.BunifuButton8.AutoRoundBorders = false;
            this.BunifuButton8.AutoSizeLeftIcon = true;
            this.BunifuButton8.AutoSizeRightIcon = true;
            this.BunifuButton8.BackColor = System.Drawing.Color.Transparent;
            this.BunifuButton8.BackColor1 = System.Drawing.Color.White;
            this.BunifuButton8.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("BunifuButton8.BackgroundImage")));
            this.BunifuButton8.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.BunifuButton8.ButtonText = "Logout";
            this.BunifuButton8.ButtonTextMarginLeft = 0;
            this.BunifuButton8.ColorContrastOnClick = 45;
            this.BunifuButton8.ColorContrastOnHover = 45;
            this.BunifuButton8.Cursor = System.Windows.Forms.Cursors.Hand;
            borderEdges2.BottomLeft = true;
            borderEdges2.BottomRight = true;
            borderEdges2.TopLeft = true;
            borderEdges2.TopRight = true;
            this.BunifuButton8.CustomizableEdges = borderEdges2;
            this.BunifuButton8.DialogResult = System.Windows.Forms.DialogResult.None;
            this.BunifuButton8.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.BunifuButton8.DisabledFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.BunifuButton8.DisabledForecolor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.BunifuButton8.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton.ButtonStates.Pressed;
            this.BunifuButton8.Font = new System.Drawing.Font("Century Gothic", 14.25F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.BunifuButton8.ForeColor = System.Drawing.Color.Black;
            this.BunifuButton8.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.BunifuButton8.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.BunifuButton8.IconLeftPadding = new System.Windows.Forms.Padding(11, 3, 3, 3);
            this.BunifuButton8.IconMarginLeft = 11;
            this.BunifuButton8.IconPadding = 10;
            this.BunifuButton8.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.BunifuButton8.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.BunifuButton8.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.BunifuButton8.IconSize = 25;
            this.BunifuButton8.IdleBorderColor = System.Drawing.Color.White;
            this.BunifuButton8.IdleBorderRadius = 1;
            this.BunifuButton8.IdleBorderThickness = 1;
            this.BunifuButton8.IdleFillColor = System.Drawing.Color.White;
            this.BunifuButton8.IdleIconLeftImage = global::Capstone.Properties.Resources.exit;
            this.BunifuButton8.IdleIconRightImage = null;
            this.BunifuButton8.IndicateFocus = false;
            this.BunifuButton8.Location = new System.Drawing.Point(22, 599);
            this.BunifuButton8.Name = "BunifuButton8";
            this.BunifuButton8.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.BunifuButton8.OnDisabledState.BorderRadius = 1;
            this.BunifuButton8.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.BunifuButton8.OnDisabledState.BorderThickness = 1;
            this.BunifuButton8.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.BunifuButton8.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.BunifuButton8.OnDisabledState.IconLeftImage = null;
            this.BunifuButton8.OnDisabledState.IconRightImage = null;
            this.BunifuButton8.onHoverState.BorderColor = System.Drawing.Color.White;
            this.BunifuButton8.onHoverState.BorderRadius = 1;
            this.BunifuButton8.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.BunifuButton8.onHoverState.BorderThickness = 1;
            this.BunifuButton8.onHoverState.FillColor = System.Drawing.Color.White;
            this.BunifuButton8.onHoverState.ForeColor = System.Drawing.Color.Black;
            this.BunifuButton8.onHoverState.IconLeftImage = null;
            this.BunifuButton8.onHoverState.IconRightImage = null;
            this.BunifuButton8.OnIdleState.BorderColor = System.Drawing.Color.White;
            this.BunifuButton8.OnIdleState.BorderRadius = 1;
            this.BunifuButton8.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.BunifuButton8.OnIdleState.BorderThickness = 1;
            this.BunifuButton8.OnIdleState.FillColor = System.Drawing.Color.White;
            this.BunifuButton8.OnIdleState.ForeColor = System.Drawing.Color.Black;
            this.BunifuButton8.OnIdleState.IconLeftImage = global::Capstone.Properties.Resources.exit;
            this.BunifuButton8.OnIdleState.IconRightImage = null;
            this.BunifuButton8.OnPressedState.BorderColor = System.Drawing.Color.White;
            this.BunifuButton8.OnPressedState.BorderRadius = 1;
            this.BunifuButton8.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.BunifuButton8.OnPressedState.BorderThickness = 1;
            this.BunifuButton8.OnPressedState.FillColor = System.Drawing.Color.White;
            this.BunifuButton8.OnPressedState.ForeColor = System.Drawing.Color.Black;
            this.BunifuButton8.OnPressedState.IconLeftImage = null;
            this.BunifuButton8.OnPressedState.IconRightImage = null;
            this.BunifuButton8.Size = new System.Drawing.Size(220, 49);
            this.BunifuButton8.TabIndex = 9;
            this.BunifuButton8.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.BunifuButton8.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.BunifuButton8.TextMarginLeft = 0;
            this.BunifuButton8.TextPadding = new System.Windows.Forms.Padding(-14, 0, 0, 0);
            this.BunifuButton8.UseDefaultRadiusAndThickness = true;
            this.BunifuButton8.Click += new System.EventHandler(this.BunifuButton8_Click);
            // 
            // DashboardBtn
            // 
            this.DashboardBtn.AllowAnimations = true;
            this.DashboardBtn.AllowMouseEffects = true;
            this.DashboardBtn.AllowToggling = false;
            this.DashboardBtn.AnimationSpeed = 100;
            this.DashboardBtn.AutoGenerateColors = false;
            this.DashboardBtn.AutoRoundBorders = false;
            this.DashboardBtn.AutoSizeLeftIcon = true;
            this.DashboardBtn.AutoSizeRightIcon = true;
            this.DashboardBtn.BackColor = System.Drawing.Color.Transparent;
            this.DashboardBtn.BackColor1 = System.Drawing.Color.White;
            this.DashboardBtn.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("DashboardBtn.BackgroundImage")));
            this.DashboardBtn.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.DashboardBtn.ButtonText = "Dashboard";
            this.DashboardBtn.ButtonTextMarginLeft = 0;
            this.DashboardBtn.ColorContrastOnClick = 45;
            this.DashboardBtn.ColorContrastOnHover = 45;
            this.DashboardBtn.Cursor = System.Windows.Forms.Cursors.Hand;
            borderEdges1.BottomLeft = true;
            borderEdges1.BottomRight = true;
            borderEdges1.TopLeft = true;
            borderEdges1.TopRight = true;
            this.DashboardBtn.CustomizableEdges = borderEdges1;
            this.DashboardBtn.DialogResult = System.Windows.Forms.DialogResult.None;
            this.DashboardBtn.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.DashboardBtn.DisabledFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.DashboardBtn.DisabledForecolor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.DashboardBtn.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton.ButtonStates.Pressed;
            this.DashboardBtn.Font = new System.Drawing.Font("Century Gothic", 14.25F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.DashboardBtn.ForeColor = System.Drawing.Color.Black;
            this.DashboardBtn.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.DashboardBtn.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.DashboardBtn.IconLeftPadding = new System.Windows.Forms.Padding(11, 3, 3, 3);
            this.DashboardBtn.IconMarginLeft = 11;
            this.DashboardBtn.IconPadding = 10;
            this.DashboardBtn.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.DashboardBtn.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.DashboardBtn.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.DashboardBtn.IconSize = 25;
            this.DashboardBtn.IdleBorderColor = System.Drawing.Color.White;
            this.DashboardBtn.IdleBorderRadius = 1;
            this.DashboardBtn.IdleBorderThickness = 1;
            this.DashboardBtn.IdleFillColor = System.Drawing.Color.White;
            this.DashboardBtn.IdleIconLeftImage = global::Capstone.Properties.Resources.home1;
            this.DashboardBtn.IdleIconRightImage = null;
            this.DashboardBtn.IndicateFocus = false;
            this.DashboardBtn.Location = new System.Drawing.Point(22, 94);
            this.DashboardBtn.Name = "DashboardBtn";
            this.DashboardBtn.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.DashboardBtn.OnDisabledState.BorderRadius = 1;
            this.DashboardBtn.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.DashboardBtn.OnDisabledState.BorderThickness = 1;
            this.DashboardBtn.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.DashboardBtn.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.DashboardBtn.OnDisabledState.IconLeftImage = null;
            this.DashboardBtn.OnDisabledState.IconRightImage = null;
            this.DashboardBtn.onHoverState.BorderColor = System.Drawing.Color.White;
            this.DashboardBtn.onHoverState.BorderRadius = 1;
            this.DashboardBtn.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.DashboardBtn.onHoverState.BorderThickness = 1;
            this.DashboardBtn.onHoverState.FillColor = System.Drawing.Color.White;
            this.DashboardBtn.onHoverState.ForeColor = System.Drawing.Color.Black;
            this.DashboardBtn.onHoverState.IconLeftImage = null;
            this.DashboardBtn.onHoverState.IconRightImage = null;
            this.DashboardBtn.OnIdleState.BorderColor = System.Drawing.Color.White;
            this.DashboardBtn.OnIdleState.BorderRadius = 1;
            this.DashboardBtn.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.DashboardBtn.OnIdleState.BorderThickness = 1;
            this.DashboardBtn.OnIdleState.FillColor = System.Drawing.Color.White;
            this.DashboardBtn.OnIdleState.ForeColor = System.Drawing.Color.Black;
            this.DashboardBtn.OnIdleState.IconLeftImage = global::Capstone.Properties.Resources.home1;
            this.DashboardBtn.OnIdleState.IconRightImage = null;
            this.DashboardBtn.OnPressedState.BorderColor = System.Drawing.Color.White;
            this.DashboardBtn.OnPressedState.BorderRadius = 1;
            this.DashboardBtn.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.DashboardBtn.OnPressedState.BorderThickness = 1;
            this.DashboardBtn.OnPressedState.FillColor = System.Drawing.Color.White;
            this.DashboardBtn.OnPressedState.ForeColor = System.Drawing.Color.Black;
            this.DashboardBtn.OnPressedState.IconLeftImage = null;
            this.DashboardBtn.OnPressedState.IconRightImage = null;
            this.DashboardBtn.Size = new System.Drawing.Size(220, 49);
            this.DashboardBtn.TabIndex = 10;
            this.DashboardBtn.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.DashboardBtn.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.DashboardBtn.TextMarginLeft = 0;
            this.DashboardBtn.TextPadding = new System.Windows.Forms.Padding(10, 0, 0, 0);
            this.DashboardBtn.UseDefaultRadiusAndThickness = true;
            this.DashboardBtn.Click += new System.EventHandler(this.DashboardBtn_Click);
            // 
            // GunaElipsePanel1
            // 
            this.GunaElipsePanel1.BackColor = System.Drawing.Color.Transparent;
            this.GunaElipsePanel1.BaseColor = System.Drawing.Color.White;
            this.GunaElipsePanel1.Controls.Add(this.DashboardBtn);
            this.GunaElipsePanel1.Controls.Add(this.BunifuButton8);
            this.GunaElipsePanel1.Controls.Add(this.UsersBtn);
            this.GunaElipsePanel1.Controls.Add(this.SalesReportBtn);
            this.GunaElipsePanel1.Controls.Add(this.SalesBtn);
            this.GunaElipsePanel1.Controls.Add(this.InventoryBtn);
            this.GunaElipsePanel1.Controls.Add(this.ItemsBtn);
            this.GunaElipsePanel1.Controls.Add(this.CategoriesBtn);
            this.GunaElipsePanel1.Controls.Add(this.Label1);
            this.GunaElipsePanel1.Controls.Add(this.BunifuPictureBox1);
            this.GunaElipsePanel1.Location = new System.Drawing.Point(12, 23);
            this.GunaElipsePanel1.Name = "GunaElipsePanel1";
            this.GunaElipsePanel1.Radius = 15;
            this.GunaElipsePanel1.Size = new System.Drawing.Size(275, 672);
            this.GunaElipsePanel1.TabIndex = 26;
            // 
            // label4
            // 
            this.label4.AutoSize = true;
            this.label4.Font = new System.Drawing.Font("Poppins", 14.25F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.label4.ForeColor = System.Drawing.Color.Black;
            this.label4.Location = new System.Drawing.Point(8, 10);
            this.label4.Name = "label4";
            this.label4.Size = new System.Drawing.Size(444, 33);
            this.label4.TabIndex = 21;
            this.label4.Text = "Dashboard / Categories / Add new Category\r\n";
            // 
            // gunaElipsePanel2
            // 
            this.gunaElipsePanel2.BackColor = System.Drawing.Color.Transparent;
            this.gunaElipsePanel2.BaseColor = System.Drawing.Color.White;
            this.gunaElipsePanel2.Controls.Add(this.label4);
            this.gunaElipsePanel2.Location = new System.Drawing.Point(300, 109);
            this.gunaElipsePanel2.Name = "gunaElipsePanel2";
            this.gunaElipsePanel2.Radius = 7;
            this.gunaElipsePanel2.Size = new System.Drawing.Size(986, 52);
            this.gunaElipsePanel2.TabIndex = 27;
            // 
            // label5
            // 
            this.label5.AutoSize = true;
            this.label5.Font = new System.Drawing.Font("Poppins", 14.25F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.label5.ForeColor = System.Drawing.Color.Black;
            this.label5.Location = new System.Drawing.Point(8, 19);
            this.label5.Name = "label5";
            this.label5.Size = new System.Drawing.Size(165, 33);
            this.label5.TabIndex = 21;
            this.label5.Text = "Add Categories";
            // 
            // label6
            // 
            this.label6.AutoSize = true;
            this.label6.Font = new System.Drawing.Font("Poppins", 12F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.label6.ForeColor = System.Drawing.Color.Black;
            this.label6.Location = new System.Drawing.Point(274, 90);
            this.label6.Name = "label6";
            this.label6.Size = new System.Drawing.Size(139, 28);
            this.label6.TabIndex = 21;
            this.label6.Text = "Category Name";
            // 
            // categoryNameTxt
            // 
            this.categoryNameTxt.AcceptsReturn = false;
            this.categoryNameTxt.AcceptsTab = false;
            this.categoryNameTxt.AnimationSpeed = 200;
            this.categoryNameTxt.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.categoryNameTxt.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.categoryNameTxt.BackColor = System.Drawing.Color.Transparent;
            this.categoryNameTxt.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("categoryNameTxt.BackgroundImage")));
            this.categoryNameTxt.BorderColorActive = System.Drawing.Color.FromArgb(((int)(((byte)(222)))), ((int)(((byte)(196)))), ((int)(((byte)(125)))));
            this.categoryNameTxt.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.categoryNameTxt.BorderColorHover = System.Drawing.Color.FromArgb(((int)(((byte)(222)))), ((int)(((byte)(196)))), ((int)(((byte)(125)))));
            this.categoryNameTxt.BorderColorIdle = System.Drawing.Color.FromArgb(((int)(((byte)(222)))), ((int)(((byte)(196)))), ((int)(((byte)(125)))));
            this.categoryNameTxt.BorderRadius = 6;
            this.categoryNameTxt.BorderThickness = 2;
            this.categoryNameTxt.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.categoryNameTxt.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.categoryNameTxt.DefaultFont = new System.Drawing.Font("Poppins", 12F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.categoryNameTxt.DefaultText = "";
            this.categoryNameTxt.FillColor = System.Drawing.Color.White;
            this.categoryNameTxt.HideSelection = true;
            this.categoryNameTxt.IconLeft = null;
            this.categoryNameTxt.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.categoryNameTxt.IconPadding = 10;
            this.categoryNameTxt.IconRight = null;
            this.categoryNameTxt.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.categoryNameTxt.Lines = new string[0];
            this.categoryNameTxt.Location = new System.Drawing.Point(279, 122);
            this.categoryNameTxt.MaxLength = 32767;
            this.categoryNameTxt.MinimumSize = new System.Drawing.Size(1, 1);
            this.categoryNameTxt.Modified = false;
            this.categoryNameTxt.Multiline = false;
            this.categoryNameTxt.Name = "categoryNameTxt";
            stateProperties5.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(222)))), ((int)(((byte)(196)))), ((int)(((byte)(125)))));
            stateProperties5.FillColor = System.Drawing.Color.Empty;
            stateProperties5.ForeColor = System.Drawing.Color.Empty;
            stateProperties5.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.categoryNameTxt.OnActiveState = stateProperties5;
            stateProperties6.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            stateProperties6.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            stateProperties6.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(109)))), ((int)(((byte)(109)))));
            stateProperties6.PlaceholderForeColor = System.Drawing.Color.DarkGray;
            this.categoryNameTxt.OnDisabledState = stateProperties6;
            stateProperties7.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(222)))), ((int)(((byte)(196)))), ((int)(((byte)(125)))));
            stateProperties7.FillColor = System.Drawing.Color.Empty;
            stateProperties7.ForeColor = System.Drawing.Color.Empty;
            stateProperties7.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.categoryNameTxt.OnHoverState = stateProperties7;
            stateProperties8.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(222)))), ((int)(((byte)(196)))), ((int)(((byte)(125)))));
            stateProperties8.FillColor = System.Drawing.Color.White;
            stateProperties8.ForeColor = System.Drawing.Color.Empty;
            stateProperties8.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.categoryNameTxt.OnIdleState = stateProperties8;
            this.categoryNameTxt.Padding = new System.Windows.Forms.Padding(3);
            this.categoryNameTxt.PasswordChar = '\0';
            this.categoryNameTxt.PlaceholderForeColor = System.Drawing.Color.Silver;
            this.categoryNameTxt.PlaceholderText = "";
            this.categoryNameTxt.ReadOnly = false;
            this.categoryNameTxt.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.categoryNameTxt.SelectedText = "";
            this.categoryNameTxt.SelectionLength = 0;
            this.categoryNameTxt.SelectionStart = 0;
            this.categoryNameTxt.ShortcutsEnabled = true;
            this.categoryNameTxt.Size = new System.Drawing.Size(442, 44);
            this.categoryNameTxt.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Bunifu;
            this.categoryNameTxt.TabIndex = 22;
            this.categoryNameTxt.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.categoryNameTxt.TextMarginBottom = 0;
            this.categoryNameTxt.TextMarginLeft = 3;
            this.categoryNameTxt.TextMarginTop = 0;
            this.categoryNameTxt.TextPlaceholder = "";
            this.categoryNameTxt.UseSystemPasswordChar = false;
            this.categoryNameTxt.WordWrap = true;
            // 
            // label7
            // 
            this.label7.AutoSize = true;
            this.label7.Font = new System.Drawing.Font("Poppins", 12F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.label7.ForeColor = System.Drawing.Color.Black;
            this.label7.Location = new System.Drawing.Point(274, 197);
            this.label7.Name = "label7";
            this.label7.Size = new System.Drawing.Size(181, 28);
            this.label7.TabIndex = 21;
            this.label7.Text = "Category Description";
            // 
            // categoryDescTxt
            // 
            this.categoryDescTxt.AcceptsReturn = false;
            this.categoryDescTxt.AcceptsTab = false;
            this.categoryDescTxt.AnimationSpeed = 200;
            this.categoryDescTxt.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.categoryDescTxt.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.categoryDescTxt.BackColor = System.Drawing.Color.Transparent;
            this.categoryDescTxt.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("categoryDescTxt.BackgroundImage")));
            this.categoryDescTxt.BorderColorActive = System.Drawing.Color.FromArgb(((int)(((byte)(222)))), ((int)(((byte)(196)))), ((int)(((byte)(125)))));
            this.categoryDescTxt.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.categoryDescTxt.BorderColorHover = System.Drawing.Color.FromArgb(((int)(((byte)(222)))), ((int)(((byte)(196)))), ((int)(((byte)(125)))));
            this.categoryDescTxt.BorderColorIdle = System.Drawing.Color.FromArgb(((int)(((byte)(222)))), ((int)(((byte)(196)))), ((int)(((byte)(125)))));
            this.categoryDescTxt.BorderRadius = 6;
            this.categoryDescTxt.BorderThickness = 2;
            this.categoryDescTxt.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.categoryDescTxt.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.categoryDescTxt.DefaultFont = new System.Drawing.Font("Poppins", 12F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.categoryDescTxt.DefaultText = "";
            this.categoryDescTxt.FillColor = System.Drawing.Color.White;
            this.categoryDescTxt.HideSelection = true;
            this.categoryDescTxt.IconLeft = null;
            this.categoryDescTxt.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.categoryDescTxt.IconPadding = 10;
            this.categoryDescTxt.IconRight = null;
            this.categoryDescTxt.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.categoryDescTxt.Lines = new string[0];
            this.categoryDescTxt.Location = new System.Drawing.Point(279, 229);
            this.categoryDescTxt.MaxLength = 32767;
            this.categoryDescTxt.MinimumSize = new System.Drawing.Size(1, 1);
            this.categoryDescTxt.Modified = false;
            this.categoryDescTxt.Multiline = false;
            this.categoryDescTxt.Name = "categoryDescTxt";
            stateProperties1.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(222)))), ((int)(((byte)(196)))), ((int)(((byte)(125)))));
            stateProperties1.FillColor = System.Drawing.Color.Empty;
            stateProperties1.ForeColor = System.Drawing.Color.Empty;
            stateProperties1.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.categoryDescTxt.OnActiveState = stateProperties1;
            stateProperties2.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            stateProperties2.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            stateProperties2.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(109)))), ((int)(((byte)(109)))));
            stateProperties2.PlaceholderForeColor = System.Drawing.Color.DarkGray;
            this.categoryDescTxt.OnDisabledState = stateProperties2;
            stateProperties3.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(222)))), ((int)(((byte)(196)))), ((int)(((byte)(125)))));
            stateProperties3.FillColor = System.Drawing.Color.Empty;
            stateProperties3.ForeColor = System.Drawing.Color.Empty;
            stateProperties3.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.categoryDescTxt.OnHoverState = stateProperties3;
            stateProperties4.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(222)))), ((int)(((byte)(196)))), ((int)(((byte)(125)))));
            stateProperties4.FillColor = System.Drawing.Color.White;
            stateProperties4.ForeColor = System.Drawing.Color.Empty;
            stateProperties4.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.categoryDescTxt.OnIdleState = stateProperties4;
            this.categoryDescTxt.Padding = new System.Windows.Forms.Padding(3);
            this.categoryDescTxt.PasswordChar = '\0';
            this.categoryDescTxt.PlaceholderForeColor = System.Drawing.Color.Silver;
            this.categoryDescTxt.PlaceholderText = "";
            this.categoryDescTxt.ReadOnly = false;
            this.categoryDescTxt.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.categoryDescTxt.SelectedText = "";
            this.categoryDescTxt.SelectionLength = 0;
            this.categoryDescTxt.SelectionStart = 0;
            this.categoryDescTxt.ShortcutsEnabled = true;
            this.categoryDescTxt.Size = new System.Drawing.Size(442, 44);
            this.categoryDescTxt.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Bunifu;
            this.categoryDescTxt.TabIndex = 22;
            this.categoryDescTxt.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.categoryDescTxt.TextMarginBottom = 0;
            this.categoryDescTxt.TextMarginLeft = 3;
            this.categoryDescTxt.TextMarginTop = 0;
            this.categoryDescTxt.TextPlaceholder = "";
            this.categoryDescTxt.UseSystemPasswordChar = false;
            this.categoryDescTxt.WordWrap = true;
            // 
            // gunaElipsePanel3
            // 
            this.gunaElipsePanel3.BackColor = System.Drawing.Color.Transparent;
            this.gunaElipsePanel3.BaseColor = System.Drawing.Color.White;
            this.gunaElipsePanel3.Controls.Add(this.addCategoryBtn);
            this.gunaElipsePanel3.Controls.Add(this.loginBtn);
            this.gunaElipsePanel3.Controls.Add(this.categoryDescTxt);
            this.gunaElipsePanel3.Controls.Add(this.label7);
            this.gunaElipsePanel3.Controls.Add(this.categoryNameTxt);
            this.gunaElipsePanel3.Controls.Add(this.label6);
            this.gunaElipsePanel3.Controls.Add(this.label5);
            this.gunaElipsePanel3.Location = new System.Drawing.Point(300, 176);
            this.gunaElipsePanel3.Name = "gunaElipsePanel3";
            this.gunaElipsePanel3.Radius = 9;
            this.gunaElipsePanel3.Size = new System.Drawing.Size(986, 472);
            this.gunaElipsePanel3.TabIndex = 29;
            // 
            // addCategoryBtn
            // 
            this.addCategoryBtn.AnimationHoverSpeed = 0.07F;
            this.addCategoryBtn.AnimationSpeed = 0.03F;
            this.addCategoryBtn.BackColor = System.Drawing.Color.Transparent;
            this.addCategoryBtn.BaseColor = System.Drawing.Color.FromArgb(((int)(((byte)(222)))), ((int)(((byte)(196)))), ((int)(((byte)(125)))));
            this.addCategoryBtn.BorderColor = System.Drawing.Color.Black;
            this.addCategoryBtn.Cursor = System.Windows.Forms.Cursors.Hand;
            this.addCategoryBtn.DialogResult = System.Windows.Forms.DialogResult.None;
            this.addCategoryBtn.FocusedColor = System.Drawing.Color.Empty;
            this.addCategoryBtn.Font = new System.Drawing.Font("Poppins", 14.25F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.addCategoryBtn.ForeColor = System.Drawing.Color.White;
            this.addCategoryBtn.Image = null;
            this.addCategoryBtn.ImageSize = new System.Drawing.Size(20, 20);
            this.addCategoryBtn.Location = new System.Drawing.Point(279, 328);
            this.addCategoryBtn.Name = "addCategoryBtn";
            this.addCategoryBtn.OnHoverBaseColor = System.Drawing.Color.FromArgb(((int)(((byte)(222)))), ((int)(((byte)(196)))), ((int)(((byte)(125)))));
            this.addCategoryBtn.OnHoverBorderColor = System.Drawing.Color.Black;
            this.addCategoryBtn.OnHoverForeColor = System.Drawing.Color.White;
            this.addCategoryBtn.OnHoverImage = null;
            this.addCategoryBtn.OnPressedColor = System.Drawing.Color.Black;
            this.addCategoryBtn.Radius = 5;
            this.addCategoryBtn.Size = new System.Drawing.Size(219, 49);
            this.addCategoryBtn.TabIndex = 24;
            this.addCategoryBtn.Text = "Add Category";
            this.addCategoryBtn.TextAlign = System.Windows.Forms.HorizontalAlignment.Center;
            this.addCategoryBtn.TextRenderingHint = Guna.UI.WinForms.DrawingTextRenderingHint.AntiAlias;
            this.addCategoryBtn.Click += new System.EventHandler(this.addCategoryBtn_Click);
            // 
            // New_Category
            // 
            this.AutoScaleDimensions = new System.Drawing.SizeF(6F, 13F);
            this.AutoScaleMode = System.Windows.Forms.AutoScaleMode.Font;
            this.BackColor = System.Drawing.Color.FromArgb(((int)(((byte)(222)))), ((int)(((byte)(196)))), ((int)(((byte)(125)))));
            this.ClientSize = new System.Drawing.Size(1309, 718);
            this.Controls.Add(this.gunaElipsePanel3);
            this.Controls.Add(this.gunaElipsePanel2);
            this.Controls.Add(this.GunaElipsePanel1);
            this.Controls.Add(this.gunaControlBox2);
            this.Controls.Add(this.gunaControlBox1);
            this.Controls.Add(this.GunaPictureBox5);
            this.Controls.Add(this.profilePicBox);
            this.Controls.Add(this.Label3);
            this.Controls.Add(this.Label2);
            this.FormBorderStyle = System.Windows.Forms.FormBorderStyle.None;
            this.Name = "New_Category";
            this.StartPosition = System.Windows.Forms.FormStartPosition.CenterScreen;
            this.Text = "New_Category";
            ((System.ComponentModel.ISupportInitialize)(this.profilePicBox)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.GunaPictureBox5)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.BunifuPictureBox1)).EndInit();
            this.GunaElipsePanel1.ResumeLayout(false);
            this.GunaElipsePanel1.PerformLayout();
            this.gunaElipsePanel2.ResumeLayout(false);
            this.gunaElipsePanel2.PerformLayout();
            this.gunaElipsePanel3.ResumeLayout(false);
            this.gunaElipsePanel3.PerformLayout();
            this.ResumeLayout(false);
            this.PerformLayout();

        }

        #endregion

        private Guna.UI.WinForms.GunaElipse gunaElipse1;
        private Guna.UI.WinForms.GunaDragControl gunaDragControl1;
        private Guna.UI.WinForms.GunaButton loginBtn;
        private Guna.UI.WinForms.GunaElipsePanel gunaElipsePanel3;
        private Bunifu.UI.WinForms.BunifuTextBox categoryDescTxt;
        internal System.Windows.Forms.Label label7;
        private Bunifu.UI.WinForms.BunifuTextBox categoryNameTxt;
        internal System.Windows.Forms.Label label6;
        internal System.Windows.Forms.Label label5;
        private Guna.UI.WinForms.GunaElipsePanel gunaElipsePanel2;
        internal System.Windows.Forms.Label label4;
        internal Guna.UI.WinForms.GunaElipsePanel GunaElipsePanel1;
        internal Bunifu.UI.WinForms.BunifuButton.BunifuButton DashboardBtn;
        internal Bunifu.UI.WinForms.BunifuButton.BunifuButton BunifuButton8;
        internal Bunifu.UI.WinForms.BunifuButton.BunifuButton UsersBtn;
        internal Bunifu.UI.WinForms.BunifuButton.BunifuButton SalesReportBtn;
        internal Bunifu.UI.WinForms.BunifuButton.BunifuButton SalesBtn;
        internal Bunifu.UI.WinForms.BunifuButton.BunifuButton InventoryBtn;
        internal Bunifu.UI.WinForms.BunifuButton.BunifuButton ItemsBtn;
        internal Bunifu.UI.WinForms.BunifuButton.BunifuButton CategoriesBtn;
        internal System.Windows.Forms.Label Label1;
        internal Bunifu.UI.WinForms.BunifuPictureBox BunifuPictureBox1;
        private Guna.UI.WinForms.GunaControlBox gunaControlBox2;
        private Guna.UI.WinForms.GunaControlBox gunaControlBox1;
        internal Guna.UI.WinForms.GunaPictureBox GunaPictureBox5;
        internal Bunifu.UI.WinForms.BunifuPictureBox profilePicBox;
        internal System.Windows.Forms.Label Label3;
        internal System.Windows.Forms.Label Label2;
        private Guna.UI.WinForms.GunaButton addCategoryBtn;
    }
}